import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Thapelo's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://www.sovtech.co.za/wp-content/uploads/sites/29/2019/07/sovtech_favicon.png" />
      </Head>
    
      {/* <header className={styles.header}>
        <div className={styles.leftnav}>
            <a href="/">T</a>
        </div>

        <div className={styles.rightnav}>
          <a href="#">Contact</a>
        </div>
      </header> */}

      <main className={styles.main}>

        <section className={styles.intro}>
          <img src="/profile-img.jpg" alt="Picture of Thapelo"/>

          <h1>Hi ABC team</h1>
          <h2>I am Thapelo.</h2>
          <p>I enjoy playing the piano, but I am still learning though, hear for yourself.  </p>
          <audio src="/test-tune.wav" controls></audio>

          <p className={styles.introclear}>I am a -year-old pioneer in software deve  lopment, especially client-side development. I find that interacting with the user of the system I am designing and developing for fulfilling when I see amazement written on their face.</p>

          <p >The need for designing and developing accessible, beautiful, interactive, and efficient systems is what keeps me at night researching and learning better ways to lift the restriction on how users access to content and products we provide.</p>
        </section>

        <hr className={styles.divider}/>
        <section className={styles.aboutcontent}>
          <h3>Why work at ABC?</h3> 
          <p>Honestly speaking, I am attracted and sold the most by Sovtech's motto of developing custom solutions. I support and believe in the idea of giving organizations of different sizes a unique identity online as it does make a difference in allowing them to better connect and communicate with their users. This is a motto I can stand behind and help fulfill it.</p>

          <p>Looking at the Sovtech clients' section there are a lot of familiar brands, most I use daily. This brings a lot of curiosity and excitement when I think about being part of a team that designs and develops systems that help these brands serve us better as consumers of content and products.</p>

          <p>With the above said, I believe being part of the Sovtech team will allow me to grow as a designer/developer, in the process changing my overall world view on designing and developing systems that serve clients and their users better.</p>
        </section>

    
        
      </main>

      <footer className={styles.footer}>
          <small><p>Designed by <a href="/">Thapelo</a></p></small>
      </footer>
    </div>
  )
}
